return {
    -- Food & Drinks
    apple = `prop_bar_fruit`,
    banana = `prop_bar_fruit`,
    burger = `prop_cs_burger_01`,
    cheeseburger = `prop_cs_burger_01`,
    coconut = `prop_bar_fruit`,
    coffee = `p_amb_coffeecup_01`,
    hamburger = `prop_cs_burger_01`,
    kiwi = `prop_bar_fruit`,
    kurkakola = `ng_proc_sodacan_01a`,
    orange = `prop_bar_fruit`,
    sandwich = `prop_sandwich_01`,
    steak = `prop_cs_steak`,
    strawberry = `prop_bar_fruit`,
    sugar = `prop_food_sugarjar`,
    tosti = `prop_sandwich_01`,
    twerks_candy = `ng_proc_candy01a`,
    water = `prop_ld_flow_bottle`,
    water_bottle = `prop_ld_flow_bottle`,
    watermelon = `prop_bar_fruit`,

    -- Alcoholic Beverages
    appledrink = `prop_drink_whisky`,
    bananadrink = `prop_drink_whisky`,
    beer = `prop_prop_beer_pissh`,
    brandy = `prop_drink_whisky`,
    daquiri = `prop_bar_fruit`,
    grapejuice = `prop_wine_bot_01`,
    orangedrink = `prop_drink_whisky`,
    tequila = `prop_drink_whtwine`,
    vodka = `prop_vodka_bottle`,
    whiterum = `prop_drink_whisky`,
    whiskey = `prop_bottle_richard`,
    whiskey_macbeth = `prop_drink_whisky`,
    whiskey_mount = `prop_drink_whisky`,
    whiskey_richards = `prop_drink_whisky`,
    wine = `prop_wine_bot_01`,
    wine_red = `prop_drink_redwine`,
    wine_rose = `prop_drink_whtwine`,
    wine_white = `prop_drink_whtwine`,

    -- Drugs & Medications
    bandage = `prop_cs_pills`,
    cokebaggy = `prop_meth_bag_01`,
    firstaid = `prop_cs_pills`,
    ifaks = `prop_cs_pills`,
    joint = `p_amb_joint_01`,
    meth = `prop_meth_bag_01`,
    painkillers = `prop_cs_pills`,
    weed_skunk = `prop_weed_bottle`,

    -- Smoking Items
    cigar = `prop_sh_cigar_01`,
    cigarette = `prop_cs_ciggy_01b`,
    rolling_paper = `p_cs_papers_01`,

    -- Weapons (Melee)
    weapon_bat = `p_cs_bbbat_01`,
    weapon_battleaxe = `prop_tool_fireaxe`,
    weapon_bottle = `prop_w_me_bottle`,
    weapon_bread = `v_ret_247_bread1`,
    weapon_crowbar = `prop_ing_crowbar`,
    weapon_dagger = `prop_w_me_dagger`,
    weapon_golfclub = `prop_golf_iron_01`,
    weapon_hammer = `prop_tool_hammer`,
    weapon_hatchet = `prop_w_me_hatchet`,
    weapon_katana = `w_me_katana`,
    weapon_karambit = `w_me_karambit`,
    weapon_keyboard = `w_me_keyboard`,
    weapon_knife = `prop_cs_bowie_knife`,
    weapon_machete = `prop_ld_w_me_machette`,
    weapon_nightstick = `w_me_nightstick`,
    weapon_poolcue = `prop_pool_cue`,
    weapon_shiv = `w_me_shiv`,
    weapon_sledgehammer = `prop_tool_sledgeham`,
    weapon_wrench = `prop_tool_wrench`,

    -- Weapons (Handguns)
    weapon_combatpistol = `w_pi_combatpistol`,
    weapon_deagle = `deserteagle`,
    weapon_fnx45 = `w_pi_fnx45`,
    weapon_glock17 = `w_pi_glock17_luxe`,
    weapon_glock18c = `w_pi_glock18c`,
    weapon_glock19gen4 = `glock19gen4`,
    weapon_glock20 = `glock20`,
    weapon_glock22 = `w_pi_glock22`,
    weapon_heavypistol = `w_pi_heavypistol`,
    weapon_m1911 = `w_pi_m1911`,
    weapon_pistol = `w_pi_combatpistol_luxe`,
    weapon_pistol50 = `w_pi_pistol50`,
    weapon_pistol_mk2 = `weapon_pistol_mk2`,
    weapon_revolver = `w_pi_heavypistol`,
    weapon_snspistol = `w_pi_sns_pistol`,
    weapon_stungun = `w_pi_stungun`,
    weapon_vintagepistol = `w_pi_vintage_pistol`,

    -- Weapons (SMGs)
    weapon_assaultsmg = `w_sb_smg`,
    weapon_combatpdw = `w_sb_smg`,
    weapon_mac10 = `w_sb_mac10`,
    weapon_machinepistol = `w_pi_appistol`,
    weapon_microsmg = `w_sb_microsmg`,
    weapon_minismg = `w_sb_smg`,
    weapon_pmxfm = `pmx`,
    weapon_smg = `w_sb_smg`,
    weapon_smg_mk2 = `w_sb_smg`,

    -- Weapons (Shotguns)
    weapon_dbshotgun = `w_sg_pumpshotgun`,
    weapon_musket = `w_ar_musket`,
    weapon_pumpshotgun = `w_sg_pumpshotgun`,
    weapon_sawnoffshotgun = `w_sg_sawnoff`,

    -- Weapons (Rifles)
    weapon_advancedrifle = `w_ar_advancedrifle`,
    weapon_ak47 = `w_ar_ak47`,
    weapon_ak74 = `w_ar_ak74`,
    weapon_aks74 = `w_ar_assaultrifle_aks74`,
    weapon_assaultrifle = `w_ar_assaultrifle`,
    weapon_assaultrifle_mk2 = `w_ar_assaultrifle`,
    weapon_bullpuprifle = `w_ar_bullpuprifle`,
    weapon_carbinerifle = `w_ar_carbinerifle`,
    weapon_carbinerifle_mk2 = `w_ar_carbinerifle`,
    weapon_groza = `w_ar_groza`,
    weapon_m4 = `w_ar_m4`,
    weapon_m6ic = `m6ic`,
    weapon_mk47fm = `MK47FluffysMods`,
    weapon_scarh = `w_ar_scarh`,
    weapon_scarsc = `scarsc`,
    weapon_specialcarbine = `w_ar_specialcarbine`,

    -- Weapons (Sniper)
    weapon_heavysniper = `w_sr_heavysniper`,
    weapon_heavysniper_mk2 = `w_sr_heavysniper`,
    weapon_marksmanrifle = `w_sr_marksmanrifle`,
    weapon_marksmanrifle_mk2 = `w_sr_marksmanrifle`,
    weapon_sniperrifle = `w_sr_sniperrifle`,

    -- Weapons (Other)
    weapon_briefcase = `prop_security_case_01`,
    weapon_briefcase_02 = `prop_security_case_01`,
    weapon_garbagebag = `prop_rub_binbag_sd_01`,
    weapon_handcuffs = `prop_cs_cuffs_01`,
    weapon_petrolcan = `prop_jerrycan_01a`,

    -- Airsoft Weapons
    weapon_airsoftak47 = `airsoftak`,
    weapon_airsoftg36c = `airsoftg36`,
    weapon_airsoftglock20 = `airsoftglock20`,
    weapon_airsoftm249 = `airsoftm249`,
    weapon_airsoftm4 = `airsoftm4a1`,
    weapon_airsoftmicrouzi = `airsoftmicrouzi`,
    weapon_airsoftmp5 = `airsoftmp5`,
    weapon_airsoftr700 = `airsoftr700`,
    weapon_airsoftr870 = `airsoft870`,

    -- Throwables
    weapon_grenade = `w_ex_grenadefrag`,
    weapon_molotov = `w_ex_molotov`,
    weapon_smokegrenade = `w_ex_grenadesmoke`,

    -- Ammo
    mg_ammo = `prop_box_ammo01a`,
    pistol_ammo = `w_pi_pistol_mag1`,
    rifle_ammo = `w_ar_assaultrifle_mag1`,
    shotgun_ammo = `w_sg_assaultshotgun_mag1`,
    smg_ammo = `w_sb_assaultsmg_mag2`,
    snp_ammo = `prop_box_ammo01a`,

    -- Attachments (matching ox_weapons.lua format)
    at_grip = `w_at_ar_afgrip`,
    at_scope = `w_at_scope_medium`,
    at_suppressor = `w_at_ar_supp`,
    at_skin_boom = `prop_paints_can05`,
    at_skin_brushstroke = `prop_paints_can05`,
    at_skin_geometric = `prop_paints_can05`,
    at_skin_patriotic = `prop_paints_can05`,
    at_skin_woodland = `prop_paints_can05`,
    at_skin_zebra = `prop_paints_can05`,

    -- Materials
    aluminum = `prop_cs_cardbox_01`,
    aluminumoxide = `prop_cs_cardbox_01`,
    cloth = `prop_cs_cardbox_01`,
    copper = `prop_cs_cardbox_01`,
    glass = `prop_cs_cardbox_01`,
    iron = `prop_cs_cardbox_01`,
    ironoxide = `prop_cs_cardbox_01`,
    metalscrap = `prop_cs_cardbox_01`,
    plastic = `prop_cs_cardbox_01`,
    rubber = `prop_cs_cardbox_01`,
    steel = `prop_cs_cardbox_01`,

    -- Tools
    advancedlockpick = `prop_tool_screwdvr03`,
    advancedrepairkit = `prop_tool_box_06`,
    cleaningkit = `prop_rag_01`,
    doors_lockpick = `prop_tool_screwdvr03`,
    drill = `prop_tool_drill`,
    electronickit = `hei_prop_hst_usb_drive`,
    gatecrack = `hei_prop_hst_usb_drive`,
    hacking_computer = `prop_laptop_02_closed`,
    hack_laptop = `prop_laptop_02_closed`,
    jerry_can = `w_am_jerrycan`,
    laserdrill = `hei_prop_heist_drill`,
    lockpick = `prop_tool_screwdvr03`,
    repairkit = `prop_tool_box_06`,
    screwdriverset = `prop_tool_screwdvr03`,
    thermal_charge = `hei_prop_heist_thermite`,
    thermite = `hei_prop_heist_thermite`,
    trojan_usb = `hei_prop_hst_usb_drive`,

    -- ID Cards & Security
    clean_card = `p_ld_id_card_002`,
    driver_license = `prop_cs_swipe_card`,
    flyid = `prop_cs_swipe_card`,
    id_card = `p_ld_id_card_002`,
    info_usb = `hei_prop_hst_usb_drive`,
    security_card_01 = `prop_cs_r_business_card`,
    security_card_02 = `prop_cs_r_business_card`,
    security_card_03 = `prop_cs_r_business_card`,
    security_card_04 = `prop_cs_r_business_card`,

    -- Robbery Items
    eksplosiv = `prop_bomb_01`,
    empty_evidence_bag = `prop_meth_bag_01`,
    filled_evidence_bag = `prop_meth_bag_01`,
    gold_bar = `hei_prop_heist_gold_bar`,
    goldbar = `hei_prop_heist_gold_bar`,
    gold_ingot = `hei_prop_heist_gold_bar`,
    hvelv_kort = `prop_cs_r_business_card`,
    juvelen_bakrom = `prop_cs_r_business_card`,
    loot_bag = `prop_cs_heist_bag_01`,
    powder = `prop_meth_bag_01`,
    robbery_keycard_01 = `prop_cs_r_business_card`,
    robbery_keycard_02 = `prop_cs_r_business_card`,
    robbery_keycard_03 = `prop_cs_r_business_card`,
    robbery_keycard_04 = `prop_cs_r_business_card`,
    robbery_keycard_05 = `prop_cs_r_business_card`,
    robbery_keycard_06 = `prop_cs_r_business_card`,
    robbery_keycard_07 = `prop_cs_r_business_card`,
    storbank_kort = `prop_cs_r_business_card`,

    -- Jewelry & Valuables
    bracelet = `prop_jewel_03a`,
    diamond_ring = `prop_jewel_03b`,
    earings = `p_tmom_earrings_s`,
    gold_bracelet = `prop_jewel_03a`,
    gold_watch = `p_watch_06`,
    goldchain = `p_jewel_necklace01_s`,
    necklace = `p_jewel_necklace01_s`,
    rolex = `p_watch_04`,
    skull = `p_jewel_pickup33_s`,
    watch = `p_watch_04`,

    -- Medical
    armor = `prop_bodyarmour_03`,
    crutch = `prop_cs_walking_stick`,
    gas_mask = `prop_mask_test_01`,
    heavyarmor = `prop_bodyarmour_03`,
    mask = `prop_mask_test_01`,
    walkstick = `prop_cs_walking_stick`,
    wheelchair = `prop_wheelchair_01`,

    -- Electronics
    binoculars = `prop_binoc_01`,
    boombox = `prop_boombox_01`,
    coffemachine = `prop_coffee_mac_02`,
    console = `prop_console_01`,
    dj_deck = `prop_dj_deck_02`,
    fan = `prop_fan_01`,
    flat_television = `prop_tv_flat_michael`,
    hacker_phone = `prop_player_phone_01`,
    j_phone = `prop_player_phone_01`,
    laptop = `prop_laptop_02_closed`,
    monitor = `prop_monitor_w_large`,
    nikon = `prop_pap_camera_01`,
    npc_phone = `prop_player_phone_01`,
    phone = `prop_player_phone_01`,
    printer = `prop_printer_02`,
    radio = `prop_cs_walkie_talkie`,
    radio_alarm = `v_res_fa_radioalrm`,
    smalltv = `prop_tv_01`,
    tablet = `prop_cs_tablet_02`,
    tapeplayer = `prop_boombox_01`,
    television = `prop_tv_05`,
    tracker = `hei_prop_hst_usb_drive`,

    -- Miscellaneous
    basketball = `prop_bskball_01`,
    basketball_hoop = `stt_prop_hoop_small_01`,
    book = `prop_cs_stock_book`,
    bong = `prop_bong_01`,
    bunch_of_flowers = `prop_snow_flower_02`,
    contract = `prop_cd_paper_pile3`,
    cups = `prop_plastic_cup_02`,
    dogfood = `prop_paper_bag_01`,
    catfood = `prop_paper_bag_01`,
    chickenfood = `prop_paper_bag_01`,
    house_locator = `hei_prop_hst_usb_drive`,
    kq_outfitbag = `prop_cs_heist_bag_01`,
    lighter = `p_cs_lighter_01`,
    markertesedler = `prop_anim_cash_pile_01`,
    microfibercloth = `prop_rag_01`,
    notepad = `p_notepad_01_s`,
    parachute = `p_parachute_s`,
    pencil = `prop_pencil_01`,
    rentalpapers = `prop_cd_paper_pile3`,
    romantic_book = `prop_cs_stock_book`,
    rose = `prop_single_rose`,
    shampoo = `prop_toilet_shamp_01`,
    shoebox = `prop_cs_cardbox_01`,
    soap = `prop_toilet_soap_01`,
    spray = `prop_spraygun_01`,
    stickynote = `p_notepad_01_s`,
    teddy = `v_ilev_mr_rasberryclean`,
    toiletry = `prop_toilet_brush_01`,
    toothpaste = `prop_toothpaste_01`,
    towing_rope = `prop_trevor_rope_01`,

    -- Added from ox_items.lua
    testburger = `prop_cs_burger_01`,
    panties = `prop_cs_panties_02`,
    black_money = `prop_anim_cash_pile_01`,
    garbage = `prop_rub_binbag_01`,
    paperbag = `prop_paper_bag_01`,
    identification = `p_ld_id_card_002`,
    money = `prop_anim_cash_pile_01`,
    mustard = `prop_food_mustard`,
    clothing = `p_s_scuba_mask_s`,
    mastercard = `prop_cs_r_business_card`,
    scrapmetal = `prop_cs_cardbox_01`,
}